START_NAVIGATION_PLANNING = (6.5, 2.8)
FINISH_NAVIGATION_PLANNING = (6.5, -2.5)

START_NAVIGATION = (-7.5, -5.0)
FINISH_NAVIGATION = (7.5, 5.0)

TOTAL_DIRECTION = 8
North = 0
NE = 1
East = 2
SE = 3
South = 4
SW = 5
West = 6
NW = 7

WAYPOINT_RADIUS = 2
WAYPOINT_VALUE = 80
THICKNESS_WAYPOINT_LINE = 6
THICKNESS_WAYPOINT_DOTTED = 10
WAYPOINT_LINE_COLOR = (255, 132, 0)
WAYPOINT_DOTTED_COLOR = (132, 0, 255)

PATH_CLEAR_VALUE = 1
PATH_UNKNOWN_VALUE = 0
PATH_OBSTACLE_VALUE = 255
PATH_OBSTACLE_TRESHOLD = 130

RESOLUTION = 0.02
ALGORITHM_RESOLUTION = 0.2

ROBOT_VALUE = 48
ROBOT_DEFAULT_RES = 0.01
ROBOT_DOTTED_COLOR = (123, 255, 0)
ROBOT_RADIUS = int(0.5/RESOLUTION / 2 + 1)

ARBITRARY_NUMBER_TO_ADJUST = 1.5
PATH_CLEAR_THICKNESS = 1
PATH_OBSTACLE_RADIUS = int(ROBOT_RADIUS*ARBITRARY_NUMBER_TO_ADJUST // 2 + 1)