DEGREE = 10
MOVEMENT_SPEED = 2.0
SPEED_MULTIPLIER = 1.0

ROBOT_RADIUS = 0.32

TICK_RATE = 0.01
AVOID_DISTANCE = 0.05
FALLBACK_DISTANCE = 0.66
DISTANCE_THRESHOLD_TO_GOAL = 0.2
MAX_ANGLE_DEGREE_TOWARD_GOAL = 50

GO_BACKWARD_ROBOT_RADIUS = 0.25
GO_BACKWARD_OBSTACLE_DIST = 0.27
OBSTACLE_AVOID_RAYCAST_LENGTH = 1.0
MAXIMUM_DISTANCE_TOLERANCE_TO_SKIP_SOME_PATH = 0.8
